version: '3.0'
services:
  web:
    image: alexcheng/magento:1.7.0.2
    ports:
      - "8084:80"
    links:
      - db
    env_file:
      - env
    volumes:
      - /home/ubuadmin/workspace/container_storage/magento1lastcode/:/var/www/html/app/code/
  db:
    image: mysql:5.6.23
    ports:
      - "3306:3309"
    env_file:
      - env
