version: '2'
services:
  mysql_pes:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3307:3306
  prestashop_pes:
    image: prestashop/prestashop
    restart: unless-stopped
    links:
      - mysql_pes:mysql_pes
    volumes:
      - /home/tgiordmaina/workspace/containers_storage/prestashoppes:/var/www/html 
    ports:
      - 8080:80
    env_file:
      - prestashop.env
    depends_on:
      - mysql_pes 
