version: '2'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 33078:3306
    networks:
      - avasize_avnet
  presta:
    image: prestashop/prestashop:1.6
    restart: unless-stopped
    links:
      - db:db
    volumes:
      - /home/ubuadmin/workspace/container_storage/ps16/:/var/www/html
      - ./conf_file/000-default.apache.80.and.8080.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8081:80
    env_file:
      - prestashop.env
    depends_on:
      - db
    networks:
      avasize_avnet:
        aliases:
          - presta16
networks:
  avasize_avnet:
    external: true
