version: '2'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3307:3306
  presta:
    image: prestashop/prestashop:1.6
    restart: unless-stopped
    links:
      - db:db
    volumes:
      - /home/ubuadmin/workspace/container_storage/ps16/:/var/www/html
    ports:
      - 8080:80
    env_file:
      - prestashop.env
    depends_on:
      - db
