version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wp
    volumes:
      - /home/ubuadmin/workspace/container_storage/wplast/:/var/www/html
    networks:
      - avasize_avnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3308:3306
    networks:
      - avasize_avnet

networks:
  avasize_avnet:
    external: true
