version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8081:80
      - 4443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wp
    volumes:
      - /home/ubuadmin/workspace/container_storage/wplast/:/var/www/html
      - ./conf_file/ssl.conf:/etc/apache2/sites-enabled/ssl.conf
      - ./conf_file/000-default.apache.80.and.8081.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./conf_file/ssl/:/etc/apache2/ssl
      - ./conf_file/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - avasize_avnet
    command: >
      bash -c "mkdir -p /etc/apache2/ssl/ && a2enmod ssl && service apache2 restart && tail -f /dev/null"

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3308:3306
    networks:
      - avasize_avnet

networks:
  avasize_avnet:
    external: true
