version: '3.0'
services:
  web:
    image: alexcheng/magento2
    ports:
      - "8083:80"
    links:
      - db
    env_file:
      - env
    volumes:
      - /home/ubuadmin/workspace/container_storage/magentolastcode/:/var/www/html/app/code/
  db:
    image: mysql:5.6.23
    ports:
      - "3306:3308"
    env_file:
      - env
